import DesignSystemLayout from '@/components/design-system/DesignSystemLayout'
import DocPageHeader from '@/components/design-system/DocPageHeader'
import DocSection from '@/components/design-system/DocSection'
import DocLabel from '@/components/design-system/DocLabel'
import LiveMarkup from '@/components/design-system/LiveMarkup'
import ClassTable from '@/components/design-system/ClassTable'
import SourceList from '@/components/design-system/SourceList'
import DevNote from '@/components/design-system/DevNote'
import CodeBlock from '@/components/design-system/CodeBlock'
import DonateFAQ from '@/sections/DonateFAQ'
import BooksAboutIntro from '@/sections/BooksAboutIntro'

const code = (s: string) => <code className="font-mono text-xs bg-neutral-subtlest px-1.5 py-0.5">{s}</code>

/* The first three questions from DonateFAQ, verbatim. The section keeps its
   list private, so the open-state example carries its own copy. */
const openStateFaqs = [
  {
    q: 'Why does the U.S. Naval Institute need to raise funds?',
    a: 'The Naval Institute is a private, not-for-profit educational institution that receives no government funding. Donations allow us to expand our programs, preserve naval history, and continue providing the open, independent forum that has served the Sea Services since 1873.',
  },
  {
    q: 'Does the U.S. Naval Institute receive government funds?',
    a: 'No. The Naval Institute receives no government funding. It is classified by the IRS as a 501(c)(3) public charity and operates from revenues generated by book sales, membership dues, advertising income, and tax-deductible gifts.',
  },
  {
    q: "What's the easiest way to donate stocks?",
    a: 'Donating appreciated stocks directly to the Naval Institute Foundation may offer significant tax advantages. Please contact our Foundation office at (410) 295-1062 or foundation@usni.org for transfer instructions and to notify us of your intended gift.',
  },
]

/**
 * The open state of one FAQ row. No FAQ section in the prototype accepts an
 * initial-open prop (each item keeps its own `useState(false)`), so this is
 * DonateFAQ's FAQItem markup with `open` fixed to true — the same classes, in
 * the same order, nothing added. Kept to the open branch only; the closed rows
 * beside it use the closed branch.
 */
function FaqItemStatic({ q, a, open }: { q: string; a: string; open: boolean }) {
  return (
    <div className={`border-b border-border-light last:border-b-0 transition-colors ${open ? 'bg-white' : ''}`}>
      <button className="accordion-row flex items-center justify-between w-full py-4 px-4 text-left gap-4" aria-expanded={open}>
        <span className="font-body font-semibold text-base text-navy-bolder">{q}</span>
        <span className={`accordion-chevron flex-shrink-0 w-8 h-8 bg-navy-bolder text-white flex items-center justify-center transition-transform duration-200 ${open ? 'rotate-180' : ''}`}>
          <svg className="w-4 h-4" viewBox="0 0 16 16" fill="none">
            <path d="M3 6l5 5 5-5" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </span>
      </button>
      {open && (
        <div className="pt-4 pb-5 pl-4 pr-16">
          <p className="font-body text-base text-neutral-subtle leading-relaxed">{a}</p>
        </div>
      )}
    </div>
  )
}

const faqTwig = `{# One FAQ row. Build this once; DonateFAQ, BooksAboutFAQ, Archives,
   Membership and Ways to Give all render it. #}
{% set panel_id = 'faq-' ~ item.id %}
<div class="faq-item border-b border-border-light last:border-b-0 transition-colors">
  <h3 class="m-0">
    <button type="button"
            class="accordion-row flex items-center justify-between w-full py-4 px-4 text-left gap-4"
            aria-expanded="false"
            aria-controls="{{ panel_id }}">
      <span class="font-body font-semibold text-base text-navy-bolder">{{ item.question }}</span>
      <span class="accordion-chevron ..." aria-hidden="true">{# chevron svg #}</span>
    </button>
  </h3>
  {# Rendered on the server and hidden, not omitted, so aria-controls always
     resolves and the answer is in the page for search and find-in-page. #}
  <div id="{{ panel_id }}" class="pt-4 pb-5 pl-4 pr-16 flex flex-col gap-4 font-body text-base text-neutral-subtle leading-relaxed" hidden>
    {{ item.answer }}
  </div>
</div>`

const faqBehavior = `// Drupal behavior: toggle one row. Rows open independently.
Drupal.behaviors.usniAccordion = {
  attach(context) {
    once('usni-accordion', '.accordion-row', context).forEach((button) => {
      const panel = document.getElementById(button.getAttribute('aria-controls'))
      const item = button.closest('.faq-item')
      button.addEventListener('click', () => {
        const open = button.getAttribute('aria-expanded') !== 'true'
        button.setAttribute('aria-expanded', String(open))
        panel.hidden = !open
        item.classList.toggle('bg-white', open)
        button.querySelector('.accordion-chevron').classList.toggle('rotate-180', open)
      })
    })
  },
}`

export default function Accordions() {
  return (
    <DesignSystemLayout>
      <div className="max-w-container mx-auto px-6 lg:px-8 pt-12 pb-24">
        <DocPageHeader title="Accordions & Disclosure">
          <p>
            Two ways of folding content away. The FAQ accordion is a list of questions, each opening
            its own answer, marked by a square navy chevron badge. The client calls it &ldquo;our new
            component styling&rdquo; and it is the treatment every accordion on the site should take. The
            See more / See less toggle shows the first part of a block of copy and reveals the rest in
            place.
          </p>
          <p>
            The prototype has no shared accordion component. Each section carries its own copy of
            the row, and the copies have drifted. This sheet documents one canonical version of
            each pattern and lists the copies, so production can build a single template.
          </p>
        </DocPageHeader>

        {/* ── FAQ accordion ─────────────────────────────────────────────── */}
        <DocSection title="FAQ accordion">
          <div className="flex flex-col gap-8">
            <p className="font-body text-base text-neutral-subtle leading-relaxed max-w-[760px]">
              Two columns from {code('lg')} up: the section heading and a &ldquo;View All&rdquo; button on
              the left, the questions on the right. Below {code('lg')} they stack, heading first. Use it
              wherever a page answers a set of common questions. Each row opens on its own, and opening
              one does not close the others. On hover the whole row turns into a solid{' '}
              {code('#0466c8')} band with white type, and the chevron badge inverts to white with a blue
              glyph. An open row sits on white against the {code('bg-surface-subtle')} section, and its
              badge turns 180°.
            </p>

            <LiveMarkup
              label="Closed — DonateFAQ as it renders (every row starts closed; click a row to open it)"
              previewClassName="p-0 bg-white"
              defaultOpen={false}
            >
              <DonateFAQ />
            </LiveMarkup>

            <LiveMarkup
              label="Open state — first row open (reconstructed: DonateFAQ’s row markup with open = true)"
              previewClassName="p-6 lg:p-8 bg-surface-subtle"
            >
              <div className="border-t border-border-light max-w-[760px]">
                {openStateFaqs.map((f, i) => (
                  <FaqItemStatic key={f.q} q={f.q} a={f.a} open={i === 0} />
                ))}
              </div>
            </LiveMarkup>

            <DevNote title="Why the open state is reconstructed">
              <p>
                The snippet generator captures a component&rsquo;s first render, and every FAQ section
                in the prototype starts all rows closed. None of them takes an initial-open prop (each
                row holds its own {code('useState(false)')}). The open example above uses the same
                markup as DonateFAQ&rsquo;s row with {code('open')} fixed to true. The classes are
                unchanged. What changes when a row opens: the row wrapper gains {code('bg-white')},
                the chevron badge gains {code('rotate-180')}, {code('aria-expanded')} turns true, and
                the answer panel appears below the button.
              </p>
            </DevNote>

            <div>
              <DocLabel>Anatomy</DocLabel>
              <ClassTable
                rows={[
                  {
                    part: 'Section',
                    classes: 'py-16 lg:py-20 bg-surface-subtle',
                    note: <>The light band (#EEF2FF) is what lets an open row read as a white card lifted off it. BooksAboutFAQ adds {code('id="faq"')} as a jump-link target.</>,
                  },
                  {
                    part: 'Container',
                    classes: 'container-site',
                    note: '1312px max, 24px gutters, 32px from lg, none from xl.',
                  },
                  {
                    part: 'Two-column grid',
                    classes: 'grid grid-cols-1 lg:grid-cols-[380px_1fr] xl:grid-cols-[416px_1fr] gap-12 lg:gap-16',
                    note: 'One column below lg. From lg the left column is a fixed 380px (416px at xl) so the heading wraps the same way on every FAQ page, and the questions take the rest.',
                  },
                  {
                    part: 'Heading',
                    classes: 'font-headline text-3xl lg:text-4xl text-navy-bolder leading-[1.1] mb-6',
                    note: '30px, 36px from lg.',
                  },
                  {
                    part: '“View All” button',
                    classes: 'inline-flex items-center justify-center bg-navy-bolder text-white font-body font-bold text-sm tracking-[-0.3px] px-5 py-3.5 hover:bg-navy-bright transition-colors',
                    note: <>The small solid navy button (see Buttons). Hover moves to {code('navy-bright')}.</>,
                  },
                  {
                    part: 'Question list',
                    classes: 'border-t border-border-light',
                    note: 'The top rule. Each row draws its own bottom rule.',
                  },
                  {
                    part: 'Row wrapper',
                    classes: 'border-b border-border-light last:border-b-0 transition-colors',
                    note: <>Open: add {code('bg-white')}. {code('last:border-b-0')} drops the rule under the final row, so the list ends without a stray line.</>,
                  },
                  {
                    part: 'Row button',
                    classes: 'accordion-row flex items-center justify-between w-full py-4 px-4 text-left gap-4',
                    note: <>{code('.accordion-row')} (index.css) gives the hover: background {code('#0466c8')}, and white on the button&rsquo;s spans, headings and paragraphs. It is plain CSS, not utilities, because its descendant selectors have to outrank the label&rsquo;s own {code('text-navy-bolder')}. {code('gap-4')} keeps a long question off the badge.</>,
                  },
                  {
                    part: 'Question',
                    classes: 'font-body font-semibold text-base text-navy-bolder',
                    note: 'Inter 16px semibold. Long questions wrap. Because the row uses items-center, the badge centres against the whole wrapped question, not its first line.',
                  },
                  {
                    part: 'Chevron badge',
                    classes: 'accordion-chevron flex-shrink-0 w-8 h-8 bg-navy-bolder text-white flex items-center justify-center transition-transform duration-200',
                    note: <>32px square, navy, white glyph. Open: add {code('rotate-180')}; the whole badge turns, not just the glyph. On row hover {code('.accordion-chevron')} turns the badge white with a {code('#0466c8')} glyph. {code('flex-shrink-0')} keeps it square next to a long question.</>,
                  },
                  {
                    part: 'Chevron glyph',
                    classes: 'w-4 h-4',
                    note: <>Inline SVG, {code('viewBox="0 0 16 16"')}, path {code('M3 6l5 5 5-5')}, 2px stroke in {code('currentColor')}. Should carry {code('aria-hidden="true"')} (the canonical copies are missing it).</>,
                  },
                  {
                    part: 'Answer panel',
                    classes: 'pt-4 pb-5 pl-4 pr-16',
                    note: <>DonateFAQ: one paragraph. {code('pr-16')} lines the answer&rsquo;s right edge up with the inside of the badge, so the text never runs under it. For rich-text answers (links, lists, addresses), use BooksAboutFAQ&rsquo;s panel instead: {code('pt-4 pb-5 pl-4 pr-16 flex flex-col gap-4 font-body text-base text-neutral-subtle leading-relaxed')}, which spaces its child paragraphs 16px apart.</>,
                  },
                  {
                    part: 'Answer copy',
                    classes: 'font-body text-base text-neutral-subtle leading-relaxed',
                    note: <>Links inside answers use {code('.text-link')}.</>,
                  },
                ]}
              />
            </div>

            <div>
              <DocLabel>Tokens</DocLabel>
              <ul className="font-body text-sm text-neutral-subtle leading-relaxed list-disc pl-5 flex flex-col gap-1 max-w-[760px]">
                <li>Badge and question text: {code('navy-bolder')} #001845. The badge glyph and the hover type are white.</li>
                <li>Hover band and inverted glyph: {code('#0466c8')}, hard-coded in index.css. It is the same blue as the {code('navy-bright')} token.</li>
                <li>Rules: {code('border-light')} #E2E8F0. Section band: {code('surface-subtle')} #EEF2FF. Answer copy: {code('neutral-subtle')} #4E576A.</li>
              </ul>
            </div>

            <DevNote>
              <p>
                <strong>Content model.</strong> Each question and answer is an item with {code('{{ item.question }}')}{' '}
                (plain text) and {code('{{ item.answer }}')} (formatted text: answers carry links, addresses,
                lists and bold type). There are two good options. If the same answers appear on more than
                one page, use an FAQ node type with a category field and a View that filters by category
                (Donate, Press, Archives, Membership). If a page owns its own answers, use a Paragraph type
                holding a list of question/answer Paragraphs. The left column takes {code('{{ heading }}')}{' '}
                and an optional link field for the &ldquo;View All&rdquo; button ({code('{{ cta.url }}')},{' '}
                {code('{{ cta.title }}')}). Archives and Ways to Give swap that button for a paragraph of
                intro copy, so make the intro and the button both optional.
              </p>
              <p>
                <strong>Markup and accessibility.</strong> Wrap each row&rsquo;s button in a heading
                ({code('<h3>')} under the section&rsquo;s {code('<h2>')}) so the questions appear in the
                page&rsquo;s heading outline, and give it {code('type="button"')}. Give each answer panel an
                id and point the button&rsquo;s {code('aria-controls')} at it. Render every panel on the
                server with the {code('hidden')} attribute rather than leaving it out: the prototype
                unmounts closed panels, which would leave {code('aria-controls')} pointing at nothing
                and keep the answers out of find-in-page. Set {code('aria-hidden="true"')} on the chevron
                badge. Focus stays on the button when a row opens or closes. Native {code('<button>')}{' '}
                handling already covers Enter and Space.
              </p>
              <CodeBlock code={faqTwig} />
              <p>
                <strong>Behaviour.</strong> Opening a row needs a small Drupal behavior. It flips{' '}
                {code('aria-expanded')}, the panel&rsquo;s {code('hidden')}, the row&rsquo;s{' '}
                {code('bg-white')} and the badge&rsquo;s {code('rotate-180')}. Rows are independent, so
                there is no &ldquo;close the others&rdquo; logic. The hover band is pure CSS and needs no
                script.
              </p>
              <CodeBlock code={faqBehavior} />
              <p>
                <strong>Native {code('<details>')} / {code('<summary>')} as an option.</strong> A{' '}
                {code('<details>')} element per row works without JavaScript, gets keyboard and
                screen-reader support for free, and browsers open it for find-in-page. The styling
                carries over: put {code('accordion-row')} on the {code('<summary>')}, hide its marker
                ({code('list-none')} plus {code('[&::-webkit-details-marker]:hidden')}), and drive the
                badge and white background from {code('[open]')} (for example{' '}
                {code('group-open:rotate-180')} on the badge and {code('group open:bg-white')} on the{' '}
                {code('<details>')}). The trade-offs: {code('<summary>')} cannot sit inside a heading, so
                the questions drop out of the heading outline; and some screen readers announce it
                inconsistently. Either is acceptable. Pick one and use it for every FAQ.
              </p>
            </DevNote>

            <SourceList
              title="Canonical"
              items={[
                { path: 'src/sections/DonateFAQ.tsx', note: 'Spec for the row, the section and a plain-text answer.' },
                { path: 'src/sections/BooksAboutFAQ.tsx', note: 'Same row and section. Its answer panel is the one to use for rich-text answers.' },
                { path: 'src/index.css', note: '.accordion-row / .accordion-chevron hover rules (components layer), and the base button { border-radius: 0 } reset that keeps the hover band square in Safari.' },
              ]}
            />

            <SourceList
              title="Drift — copies that differ from the canonical row"
              tone="drift"
              items={[
                {
                  path: 'src/sections/MembershipFAQ.tsx',
                  note: (
                    <>
                      Badge is {code('bg-navy-subtle p-2')} (navy-subtle, padding-sized) instead of{' '}
                      {code('w-8 h-8 bg-navy-bolder')}. It turns the SVG rather than the badge, has{' '}
                      {code('aria-hidden')} on the badge, and its question is {code('font-bold')} with{' '}
                      {code('leading-[1.4] flex-1')}. Rows are {code('px-5 py-5')}, and the last row keeps its
                      bottom rule (no {code('last:border-b-0')}). The answer panel is {code('px-5 pt-4 pb-6')}.
                      Layout is a flex row with a {code('lg:w-[32%]')} left column that is{' '}
                      {code('lg:sticky lg:top-32')}, set on {code('bg-white py-section')}, with a{' '}
                      {code('text-4xl')} heading at every width and the {code('NavyButtonLink')} button
                      (text-base, px-5 py-4).
                    </>
                  ),
                },
                {
                  path: 'src/sections/ArchivesFAQ.tsx',
                  note: (
                    <>
                      Question is {code('lg:text-lg')}, spaced from the badge with {code('pr-4')} instead of{' '}
                      {code('gap-4')}. The answer panel is {code('px-4 pt-3 pb-5 pr-10')}, and an open row
                      does not turn white. It sits on {code('bg-white')}, so the open state has no lift. The
                      left column has an intro paragraph and a larger &ldquo;Contact the Archives&rdquo; button
                      ({code('text-base tracking-[-0.5px] px-6 py-4')}).
                    </>
                  ),
                },
                {
                  path: 'src/sections/GivingWaysToGive.tsx',
                  note: (
                    <>
                      Question is {code('lg:text-lg')}, and the row has no {code('gap-4')}, so a long title
                      can run up against the badge. The answer panel is {code('pr-14')}. The left column has
                      an eyebrow, a heading and a paragraph, and no button.
                    </>
                  ),
                },
                {
                  path: 'src/sections/BookProductDetails.tsx',
                  note: (
                    <>
                      A single disclosure (&ldquo;Product Details&rdquo;) that starts open ({code('useState(true)')}).
                      It uses a {code('+')} / {code('−')} text glyph in {code('text-neutral-subtle')} instead of
                      the badge, and its rule is {code('border-[#e4e7ec]')}, which has no token (border-light
                      #E2E8F0 is the nearest). Accessibility: the {code('<h2>')} is inside the{' '}
                      {code('<button>')}, which strips its heading role, so the section drops out of the
                      outline. Put the button inside the heading instead. The glyph is read aloud as
                      &ldquo;plus&rdquo; or &ldquo;minus&rdquo;, and there is no {code('aria-controls')}.
                    </>
                  ),
                },
                {
                  path: 'src/components/layout/SectionSubNav.tsx',
                  note: (
                    <>
                      On mobile the tan sub-nav folds into a toggle bar. It is a disclosure, but it uses a
                      hamburger and close icon instead of the chevron and has no {code('aria-controls')}.
                      It is documented on the Navigation sheet. Only GivingSubNav uses this shared component.
                      AboutSubNav, ArchivesSubNav, ArticleSubNav, BooksSubNav, EssayContestsSubNav,
                      NavalHistorySubNav and ProceedingsSubNav (all in {code('src/sections/')}) each carry
                      their own copy of the toggle.
                    </>
                  ),
                },
              ]}
            />
          </div>
        </DocSection>

        {/* ── Compact filter accordion ──────────────────────────────────── */}
        <DocSection title="Compact accordion — filter facets">
          <div className="flex flex-col gap-8">
            <p className="font-body text-base text-neutral-subtle leading-relaxed max-w-[760px]">
              A smaller size of the same treatment for the facet groups in a listing&rsquo;s filter sidebar
              (Event Type, Categories). It uses the same {code('.accordion-row')} hover band and{' '}
              {code('.accordion-chevron')} badge, at sidebar scale: 14px bold label, a smaller badge, and
              an optional count pill when filters in the group are on. It is not rendered here because it
              lives inside the full archive pages. See it at /events/past and /essay-contests/archive.
            </p>

            <div>
              <DocLabel>Anatomy (from PastEventsArchive)</DocLabel>
              <ClassTable
                rows={[
                  {
                    part: 'Group wrapper',
                    classes: 'border-b border-border-light',
                    note: 'No last:border-0 here: the archives have one accordion, so its bottom rule closes the group.',
                  },
                  {
                    part: 'Row button',
                    classes: 'accordion-row flex items-center justify-between w-full gap-3 px-3 py-3 font-body font-bold text-sm text-navy-bolder text-left',
                    note: <>Carries {code('aria-expanded')} and {code('aria-controls="past-events-kinds"')}. This is the most complete accessibility wiring of any accordion in the prototype.</>,
                  },
                  {
                    part: 'Count pill',
                    classes: 'font-body font-bold text-xs text-white bg-navy-subtle rounded-full px-2 py-0.5',
                    note: 'Shows how many options in the group are checked. One of the few deliberate rounded shapes.',
                  },
                  {
                    part: 'Chevron badge',
                    classes: 'accordion-chevron flex-shrink-0 flex items-center justify-center bg-navy-subtle p-1.5',
                    note: <>Padding-sized (about 26px), in {code('navy-subtle')} #023E7D rather than navy-bolder, and {code('aria-hidden="true"')}.</>,
                  },
                  {
                    part: 'Chevron glyph',
                    classes: 'w-3.5 h-3.5 text-white transition-transform duration-200',
                    note: <>Open: add {code('rotate-180')}. Here the glyph turns, not the badge.</>,
                  },
                  {
                    part: 'Panel',
                    classes: 'pb-4',
                    note: <>Has the id that {code('aria-controls')} names. It is unmounted when closed; in production, render it with {code('hidden')} instead.</>,
                  },
                ]}
              />
            </div>

            <SourceList
              title="Canonical"
              items={[{ path: 'src/sections/PastEventsArchive.tsx', note: 'AccordionChevron and the Event Type group.' }]}
            />
            <SourceList
              title="Drift"
              tone="drift"
              items={[
                {
                  path: 'src/sections/EssayContestsArchive.tsx',
                  note: 'Identical copy of AccordionChevron and the row (Categories group). It differs only in the ids.',
                },
                {
                  path: 'src/sections/BooksCollectionLayout.tsx',
                  note: (
                    <>
                      Its local {code('Accordion')} (Binding, Series, Subjects, Price) has no{' '}
                      {code('.accordion-row')} or {code('.accordion-chevron')}, so it has no hover band and no
                      badge inversion. Its button is {code('py-3')} with no horizontal padding. It has no{' '}
                      {code('aria-controls')}, it starts open ({code('defaultOpen = true')}), and its wrapper
                      uses {code('last:border-0')}.
                    </>
                  ),
                },
                {
                  path: 'src/components/ui/FilterPanel.tsx',
                  note: (
                    <>
                      The mobile &ldquo;Filters&rdquo; toggle that folds the whole sidebar below {code('lg')}. It
                      uses a {code('w-7 h-7 bg-navy-subtle')} badge with a plus/minus glyph instead of a
                      chevron, and a {code('border-b-4 border-[#0466c8]')} rule. It is wired correctly, with{' '}
                      {code('aria-controls')} from {code('useId')} and a panel that is hidden by class, not
                      unmounted.
                    </>
                  ),
                },
              ]}
            />
          </div>
        </DocSection>

        {/* ── See more / See less ───────────────────────────────────────── */}
        <DocSection title="See more / See less">
          <div className="flex flex-col gap-8">
            <p className="font-body text-base text-neutral-subtle leading-relaxed max-w-[760px]">
              A text toggle under a block of prose. The first two paragraphs show, and the rest are one
              click away, so a long introduction does not push the page&rsquo;s main content below the
              fold. The label is underlined at rest and the underline drops on hover (the reverse of{' '}
              {code('.text-link')}). A chevron after it points down when closed and up when open. Use it
              for long editorial copy that most readers will skip. Use the FAQ accordion for anything a
              reader scans for by title.
            </p>

            <LiveMarkup
              label="Collapsed — BooksAboutIntro (two paragraphs, then the toggle; click to expand)"
              previewClassName="p-0 bg-white"
            >
              <BooksAboutIntro />
            </LiveMarkup>

            <div>
              <DocLabel>Anatomy</DocLabel>
              <ClassTable
                rows={[
                  {
                    part: 'Copy column',
                    classes: 'max-w-[760px] flex flex-col gap-5 font-body text-base lg:text-[17px] text-neutral-bold leading-[1.7]',
                    note: <>The toggle sits inside the column as its last child, so it follows the copy it controls. 16px body, 17px from lg. Text is {code('neutral-bold')} #33415C.</>,
                  },
                  {
                    part: 'Revealed copy',
                    classes: '(fragment — same <p> elements as the visible paragraphs)',
                    note: 'Expanding inserts the remaining paragraphs before the toggle. They take the column’s gap, so the spacing looks the same as if the copy had never been folded.',
                  },
                  {
                    part: 'Toggle button',
                    classes: 'flex items-center gap-2 font-body font-semibold text-sm text-[#023E7D] group self-start',
                    note: <>{code('text-[#023E7D]')} is the {code('navy-subtle')} token, hard-coded. {code('self-start')} keeps the hit area to the label instead of the full column width.</>,
                  },
                  {
                    part: 'Label',
                    classes: 'underline group-hover:no-underline',
                    note: '“See more” / “See less”.',
                  },
                  {
                    part: 'Chevron',
                    classes: 'fa-solid fa-chevron-down text-xs',
                    note: <>Open: {code('fa-chevron-up')}. It carries {code('aria-hidden="true"')}.</>,
                  },
                ]}
              />
            </div>

            <DevNote>
              <p>
                <strong>Open state.</strong> The snippet shows the collapsed render. When expanded, the
                remaining paragraphs appear in place before the button, the label reads &ldquo;See
                less&rdquo;, the icon becomes {code('fa-chevron-up')}, and {code('aria-expanded')} turns
                true. No other classes change.
              </p>
              <p>
                <strong>Fields.</strong> The copy is one formatted-text field, {code('{{ body }}')}. Split
                it in the template (or with a &ldquo;summary&rdquo; field for the visible part) rather
                than asking editors for two fields. The number of visible paragraphs (two) is a template
                setting, not content.
              </p>
              <p>
                <strong>Behaviour and accessibility.</strong> Render the full copy on the server and let
                a Drupal behavior hide everything after the second paragraph and insert the button. Without
                JavaScript the reader gets the whole text and no dead control. Wrap the folded part in an
                element with an id, set {code('hidden')} on it, and give the button{' '}
                {code('type="button"')}, {code('aria-expanded')} and {code('aria-controls')}. BooksAboutIntro
                and EssayContestsAbout have {code('aria-expanded')} but no {code('aria-controls')}, and they
                unmount the hidden copy. GivingOpportunities is wired correctly: it keeps its container
                in the DOM, points {code('aria-controls')} at it, and adds an {code('sr-only')} suffix
                (&ldquo;about {'{{ title }}'}&rdquo;) so that several toggles on one page have distinct
                accessible names. Follow that model. Do not move focus on toggle.
              </p>
            </DevNote>

            <SourceList
              title="Canonical"
              items={[
                { path: 'src/sections/BooksAboutIntro.tsx', note: 'Spec for the toggle and the prose column.' },
                { path: 'src/sections/EssayContestsAbout.tsx', note: 'Identical toggle. Its column is wider (lg:max-w-[820px]) beside an image mosaic, and the revealed part ends with a seasonal note box.' },
              ]}
            />

            <SourceList
              title="Drift"
              tone="drift"
              items={[
                {
                  path: 'src/sections/GivingOpportunities.tsx',
                  note: (
                    <>
                      &ldquo;Read more&rdquo; / &ldquo;Read less&rdquo; on each of ten cards, with the same
                      classes plus {code('type="button"')}, {code('aria-controls')} and an {code('sr-only')}{' '}
                      &ldquo;about {'{title}'}&rdquo;. It differs only in its wording, and its accessibility
                      wiring is the model for the canonical toggle. Pick one wording (&ldquo;See more&rdquo;
                      or &ldquo;Read more&rdquo;) for the site.
                    </>
                  ),
                },
                {
                  path: 'src/sections/BooksCollectionLayout.tsx',
                  note: (
                    <>
                      &ldquo;See {'{n}'} more&rdquo; under a facet list of more than 12 options. It is a
                      compact list reveal, not prose: {code('mt-1.5 font-body font-semibold text-xs text-[#0466C8] hover:text-navy-subtle transition-colors')},
                      no underline, chevron {code('text-[10px] ml-1')}. It has no {code('aria-expanded')} and
                      no {code('aria-controls')}.
                    </>
                  ),
                },
                {
                  path: 'src/sections/EssayContestsArchive.tsx',
                  note: 'Same “See {n} more” facet reveal as BooksCollectionLayout (Categories, 38 series), with the same missing aria-expanded.',
                },
                {
                  path: 'src/sections/CollectionIntro.tsx',
                  note: (
                    <>
                      The series-editor bio. It is clamped with {code('line-clamp-4')} rather than split by
                      paragraph, so the whole bio stays in the DOM. The toggle is a {code('.text-link')} with
                      text glyphs (&ldquo;+ Read more&rdquo; / &ldquo;− Read less&rdquo;) and no icon. It has{' '}
                      {code('aria-expanded')} but no {code('aria-controls')}, and the glyphs are read aloud.
                    </>
                  ),
                },
                {
                  path: 'src/sections/StudentSchoolDirectory.tsx',
                  note: (
                    <>
                      &ldquo;Show / Hide {'{n}'} companies&rdquo; inside a school card:{' '}
                      {code('font-bold text-sm text-[#0466c8] hover:text-navy-bolder')}, with a chevron that
                      rotates instead of swapping icons. It has {code('aria-expanded')} but no{' '}
                      {code('aria-controls')}.
                    </>
                  ),
                },
              ]}
            />
          </div>
        </DocSection>
      </div>
    </DesignSystemLayout>
  )
}
