function DocIcon() {
  return (
    <svg className="w-5 h-5 flex-shrink-0 text-navy-subtle" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
      <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" strokeLinecap="round" strokeLinejoin="round"/>
      <polyline points="14 2 14 8 20 8" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  )
}

export default function DonateDisclosure() {
  return (
    <section className="py-16 lg:py-20 bg-white">
      <div className="container-site">
        <h2 className="font-headline text-2xl lg:text-3xl text-navy-bolder leading-[1.1] mb-8">
          Important Giving Information
        </h2>
        <div className="border-t border-border-light pt-8 flex flex-col gap-5 max-w-[860px]">
          <p className="font-body text-sm text-neutral-subtle leading-relaxed">
            The Naval Institute is a private, not-for-profit educational institution. It receives no government funding.
            Classified by the IRS as a 501(c)(3), the Institute operates from revenues generated by book sales, membership
            dues, from tax-deductible gifts made to the Naval Institute Foundation. The Naval Institute Foundation gratefully
            accepts gifts or multi-year pledges via cash, check, credit card, or appreciated stock. See the Ways To Give
            page for more information.
          </p>
          <p className="font-body text-sm text-neutral-subtle leading-relaxed">
            Leadership Circle recognizes gifts of $1,000 or more within a calendar year. It is the first of the Naval
            Institute's premier gift-recognition societies and provides donors with special courtesies and benefits. See the
            Donor Recognition page for more information.
          </p>
          <p className="font-body text-sm text-neutral-subtle leading-relaxed">
            For additional information or questions, please call Amanda Ojeda at{' '}
            <a href="tel:4102951062" className="text-navy-subtle hover:text-navy">(410) 295-1062</a>
            {' '}or{' '}
            <a href="mailto:foundation@usni.org" className="text-navy-subtle hover:text-navy">e-mail</a>
            {' '}her.
          </p>
          <a
            href="/giving/mandated-disclosure"
            className="inline-flex items-center gap-2 font-body font-semibold text-sm text-navy-subtle hover:text-navy transition-colors"
          >
            <DocIcon />
            Mandated Disclosure for Charitable Organizations
          </a>
        </div>
      </div>
    </section>
  )
}
