import { useState } from 'react'

const faqs = [
  {
    q: 'Why does the U.S. Naval Institute need to raise funds?',
    a: 'The Naval Institute is a private, not-for-profit educational institution that receives no government funding. Donations allow us to expand our programs, preserve naval history, and continue providing the open, independent forum that has served the Sea Services since 1873.',
  },
  {
    q: 'Does the U.S. Naval Institute receive government funds?',
    a: 'No. The Naval Institute receives no government funding. It is classified by the IRS as a 501(c)(3) public charity and operates from revenues generated by book sales, membership dues, advertising income, and tax-deductible gifts.',
  },
  {
    q: 'How do I help the U.S. Naval Institute continue its crucial work of providing an independent forum for the professional exchange of ideas in support of the Sea Services?',
    a: 'You can support the Naval Institute through a one-time or recurring gift, planned giving, matching gifts from your employer, gifts of securities, or by joining as a member. Every contribution — large or small — makes a difference.',
  },
  {
    q: "What's the easiest way to donate stocks?",
    a: 'Donating appreciated stocks directly to the Naval Institute Foundation may offer significant tax advantages. Please contact our Foundation office at (410) 295-1062 or foundation@usni.org for transfer instructions and to notify us of your intended gift.',
  },
  {
    q: 'How could my company benefit from a partnership with the U.S. Naval Institute?',
    a: 'Corporate partnerships with the Naval Institute provide visibility among senior military leaders, government officials, and defense professionals. Contact our corporate giving team to learn about sponsorship opportunities, event partnerships, and other programs.',
  },
  {
    q: 'How do I make a tax-deductible donation?',
    a: 'Gifts made to the U.S. Naval Institute Foundation are tax-deductible to the extent allowed by law. You will receive an acknowledgment letter for your records. Consult your tax advisor for specific guidance on your situation.',
  },
  {
    q: 'Does the Naval Institute Foundation offer grants or scholarships?',
    a: 'The Naval Institute Foundation does not currently offer public grant programs or scholarships. Our resources are directed toward the mission of the U.S. Naval Institute, including its publications, events, and educational programs.',
  },
]

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false)
  return (
    <div className={`border-b border-border-light last:border-b-0 transition-colors ${open ? 'bg-white' : ''}`}>
      <button
        className={`flex items-center justify-between w-full py-4 px-4 text-left gap-4 transition-colors ${open ? '' : 'hover:bg-white'}`}
        onClick={() => setOpen(!open)}
        aria-expanded={open}
      >
        <span className="font-body font-semibold text-base text-navy-bolder">{q}</span>
        <span className={`flex-shrink-0 w-8 h-8 bg-navy-bolder text-white flex items-center justify-center transition-transform duration-200 ${open ? 'rotate-180' : ''}`}>
          <svg className="w-4 h-4" viewBox="0 0 16 16" fill="none">
            <path d="M3 6l5 5 5-5" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
        </span>
      </button>
      {open && (
        <div className="pb-5 px-4 pr-16">
          <p className="font-body text-base text-neutral-subtle leading-relaxed">{a}</p>
        </div>
      )}
    </div>
  )
}

export default function DonateFAQ() {
  return (
    <section className="py-16 lg:py-20 bg-surface-subtle">
      <div className="container-site">
        <div className="grid grid-cols-1 lg:grid-cols-[380px_1fr] xl:grid-cols-[416px_1fr] gap-12 lg:gap-16">

          {/* Left */}
          <div>
            <h2 className="font-headline text-3xl lg:text-4xl text-navy-bolder leading-[1.1] mb-6">
              Foundation Frequently Asked Questions
            </h2>
            <a
              href="/giving/faq"
              className="inline-flex items-center justify-center bg-navy-bolder text-white font-body font-bold text-sm tracking-[-0.3px] px-5 py-3.5 hover:bg-navy-bright transition-colors"
            >
              View All Frequently Asked Questions
            </a>
          </div>

          {/* Right — accordion */}
          <div className="border-t border-border-light">
            {faqs.map((item) => (
              <FAQItem key={item.q} q={item.q} a={item.a} />
            ))}
          </div>

        </div>
      </div>
    </section>
  )
}
