import imgLeft from '@/assets/images/usni-news-article-feature-center.png'
import imgTopRight from '@/assets/images/community-modal-hero.png'
import imgBottomRight from '@/assets/images/information-modal-hero.png'

export default function GivingAbout() {
  return (
    <section id="about-the-foundation" className="py-16 lg:py-20 bg-white">
      <div className="container-site">
        <div className="grid grid-cols-1 lg:grid-cols-[1fr_420px] xl:grid-cols-[1fr_480px] gap-10 lg:gap-16">

          {/* Left — text content */}
          <div className="flex flex-col gap-6">
            <h2 className="font-headline text-4xl lg:text-5xl text-navy-bolder leading-tight">
              About the Naval Institute Foundation
            </h2>
            <p className="font-body text-base lg:text-lg text-neutral-subtle leading-relaxed">
              The Naval Institute Foundation was organized to operate exclusively to raise funds for
              the charitable and educational purposes to further the mission and policies of the
              U.S. Naval Institute. For nearly 150 years, the Naval Institute has been the
              intellectual heart of the naval profession. It gives voice to those who seek the
              finest Navy, Marine Corps, and Coast Guard.
            </p>
            <p className="font-body text-base lg:text-lg text-neutral-subtle leading-relaxed">
              At its core, the Institute is an open, independent, nonpartisan forum where those who
              dare to read, think, speak, and write can take issue with senior positions—not as an
              act of insubordination, but as a step forward to advance the understanding of sea
              power and other issues critical to global security.
            </p>
            <p className="font-body text-base lg:text-lg text-neutral-subtle leading-relaxed">
              The Naval Institute is a private, not-for-profit educational institution. It receives
              no government funding. Classified by the IRS as a 501(c)(3), the Institute operates
              from revenues generated by book sales, membership dues, advertising income, and from
              tax-deductible gifts made to the Naval Institute Foundation.
            </p>
          </div>

          {/* Right — photo grid */}
          <div className="hidden lg:grid grid-cols-2 gap-3 h-[600px]">
            {/* Left tall image */}
            <div className="overflow-hidden row-span-2">
              <img
                src={imgLeft}
                alt="Naval forces in action"
                className="w-full h-full object-cover"
              />
            </div>
            {/* Top right */}
            <div className="overflow-hidden">
              <img
                src={imgTopRight}
                alt="Naval Institute community"
                className="w-full h-full object-cover"
              />
            </div>
            {/* Bottom right */}
            <div className="overflow-hidden">
              <img
                src={imgBottomRight}
                alt="Naval Institute resources"
                className="w-full h-full object-cover"
              />
            </div>
          </div>

        </div>
      </div>
    </section>
  )
}
